version: '3'

services:
 db:
  image: mysql_db
  environment:
   -MYSQL_ROOT_PASSWORD: "123"
   -MYSQL_DATABASE: first_db
  ports:
   - "3307:3306"
 
 flask:
  image: python_app
  ports:
   - "5000:5000"
  links:
   - db 
